# # Use official Node.js image
# FROM node:18
 
# # Set working directory
# WORKDIR /app
 
# # Copy package.json and install dependencies
# COPY package.json package-lock.json ./
# RUN npm install
 
# # Copy frontend source code
# COPY . .
 
# # Build the Next.js app
# RUN npm run build
 
# RUN npm start
 
# # Expose Next.js default port
# EXPOSE 4000
 
# # Start Next.js in production mode
# CMD ["npm", "run", "start"]
 
# # Use official Node.js image
# # FROM node:18-alpine AS build
 
# # # Set working directory
# # WORKDIR /app
 
# # # Copy package.json and install dependencies
# # COPY package.json package-lock.json ./
# # RUN npm install --frozen-lockfile
 
# # # Copy frontend source code
# # COPY . .
 
# # # Build the Next.js app
# # RUN npm run build
 
# # # Use a smaller production image
# # FROM node:18-alpine
 
# # WORKDIR /app
 
# # # Copy only necessary files from the build stage
# # COPY --from=build /app/package.json /app/package-lock.json ./
# # RUN npm install --frozen-lockfile --production
 
# # # Copy the built Next.js app
# # COPY --from=build /app/.next /app/.next
# # COPY --from=build /app/public /app/public
# # COPY --from=build /app/node_modules /app/node_modules
# # COPY --from=build /app/.env /app/.env
 
# # # Expose Next.js default port
# # EXPOSE 4000
 
# # # Start Next.js in production mode
# # CMD ["npm", "run", "start"]
 
# Use official Node.js image
FROM node:18 AS build
 
# Set working directory
WORKDIR /app
 
# Copy package.json and install dependencies
COPY package.json package-lock.json ./
 
RUN npm install --frozen-lockfile
 
# Copy frontend source code
COPY . .
 
# Build the Next.js app
RUN npm run build
 
# Use a smaller production image
FROM node:18-alpine AS production
 
WORKDIR /app
 
# Copy only necessary files from the build stage
COPY --from=build /app/package.json /app/package-lock.json ./
RUN npm install --frozen-lockfile --production
 
# Copy the built Next.js app
COPY --from=build /app/.next /app/.next
COPY --from=build /app/public /app/public
COPY --from=build /app/node_modules /app/node_modules
 
# Expose Next.js default port
EXPOSE 3000
 
# Start Next.js in production mode
CMD ["npm", "run", "start"]